// src/app/layout.tsx
import type { Metadata } from "next";
// *** Corrected Import Path ***
// Assuming globals.css is directly inside src/app/
import "./globals.css"; 

export const metadata: Metadata = {
  title: "ArtisanCMS", // Or your client's business name later
  description: "Generated by ArtisanCMS", // Or your client's description
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* The body tag applies default styles but NO logic */}
      <body>{children}</body> 
    </html>
  );
}