// src/app/layout.tsx
import { Analytics } from "@vercel/analytics/next"
import type { Metadata } from "next";
import "./globals.css"; 

export const metadata: Metadata = {
  title: "ArtisanCMS",
  description: "Generated by ArtisanCMS",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body> 
    </html>
  );
}