import type { Metadata } from "next";
// *** Corrected Import Path ***
// Assuming globals.css is directly inside src/app/
import "./globals.css";
import CookieConsentBanner from "@/components/CookieConsentBanner";

export const metadata: Metadata = {
  title: "ArtisanCMS", // Or your client's business name later
  description: "Generated by ArtisanCMS", // Or your client's description
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* The body tag applies default styles but NO logic */}
      <body className="bg-transparent text-slate-900">
        <a href="#main-content" className="skip-link">
          Zum Inhalt springen
        </a>
        <div id="main-content" className="min-h-screen">
          {children}
        </div>
        <CookieConsentBanner />
      </body>
    </html>
  );
}

